### PR TITLE
Add support for some additional diff types

### PR DESCRIPTION
**Pull request by gburgett**
Hello,

We've encountered some additional diffs in the wild that are not properly handled by this parser.  I've added test cases and support for those diffs so this parser will not blow up.

### CODE REVIEW

**Comment by anolson** [comment]
Hi 👋 

This looks pretty good, I'll take a closer look this evening.

I guess I activated Hound for this repo at some point. I wouldn't worry about too much about those comments, but feel free to fix any of them up.

**Comment by gburgett** [comment]
I went ahead and fixed the string literals to make them consistent.  The regular expression style I used is consistent with the rest of that file.

Thanks for taking a look!

**Comment by anolson** [comment]
👍

**Comment by anolson** [comment]
I just pushed `0.4.0` to rubygems.org that should include these changes.

https://rubygems.org/gems/git_diff/versions/0.4.0

**Pull request merged**
